### GET request to example server
# curl -X POST http://localhost:8080/api/calculate
#
#  -u username:password
#  -H "Content-Type: application/json"
#  -d '{"from":"USD", "to":"EUR", "amount":100}'
# curl --location 'http://localhost:8080/api/calculate'
#--header 'Content-Type: application/json'
#--header 'Authorization: Basic dXNlcjplZGZhNjJhZS1iNjk4LTQwY2ItOWYzZS00MGJkYmUyOTJiMDE='
#--header 'Cookie: JSESSIONID=CED6AC11A966B1CCE4E0049FE60D15A2'
#--data '{
#  "customer": {
#    "userType": "EMPLOYEE",
#    "tenure": 3.0
#  },
#  "items": [
#    {
#      "name": "Pencil",
#      "quantity": 10,
#      "category": "OTHER",
#      "amount": 200.00
#    }
#  ],
#  "targetCurrency": "EUR",
#  "originalCurrency": "USD",
#  "totalAmount": 200.00
#}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              '
POST http://localhost:8080/api/calculate
Authorization: Basic dXNlcjplZGZhNjJhZS1iNjk4LTQwY2ItOWYzZS00MGJkYmUyOTJiMDE=
Content-Type: application/json

{
  "customer": {
    "userType": "EMPLOYEE",
    "tenure": 3.0
  },
  "items": [
    {
      "name": "Pencil",
      "quantity": 10,
      "category": "OTHER",
      "amount": 200.00
    }
  ],
  "targetCurrency": "EUR",
  "originalCurrency": "USD",
  "totalAmount": 200.00
}

###



###



###